# Changes here will be overwritten by Copier
_commit: v0.1.0
_src_path: git+ssh://git@github.com/eduardokairalla1/fastapi-project-starter.git
author_name: Eduardo Kairalla
base_image: python:3.13.7-slim-bookworm
ci_image: ci/py313-slim-bookworm
description: This is a REST API backend for OPTY project
name: opty_api

